IBUsername=YOUR_USERNAME  # 會被 Docker 自動替換
IBPassword=YOUR_PASSWORD  # 會被 Docker 自動替換
IBCWrapper=com.ib.client.EWrapper
# 這裡要跟 main.py 的連接埠一致
IbPort=4002 
ExistingSessionDetectedAction=primary
# 自動接受 API 連線
AcceptIncomingConnection=yes
AcceptOrders=yes